name: default
on: [pull_request, push]
jobs:
  lint:
    runs-on: [self-hosted, X64, Linux]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      env:
        REQUIREMENTS_FILE: lint
      run: |
        python -m pip install -U pip setuptools
        set -e
        python -m pip install -U -r requirements/${REQUIREMENTS_FILE}.txt
    - name: Lint with flake8
      run: |
        if [ "$GITHUB_EVENT_NAME" == "pull_request" -a -n "$GITHUB_HEAD_REF" ]; then
          echo "(skipping matchers for pull request from local branches)"
        else
          echo "::add-matcher::.github/workflows/flake8-matcher.json"
        fi
        python -m flake8 src/ tests
  typecheck:
    runs-on: [self-hosted, X64, Linux]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      env:
        REQUIREMENTS_FILE: typecheck
      run: |
        python -m pip install -U pip setuptools
        python -m pip install -U -r requirements/${REQUIREMENTS_FILE}.txt
    - name: Type check with mypy
      run: |
        if [ "$GITHUB_EVENT_NAME" == "pull_request" -a -n "$GITHUB_HEAD_REF" ]; then
          echo "(skipping matchers for pull request from local branches)"
        else
          echo "::add-matcher::.github/workflows/mypy-matcher.json"
        fi
        python -m mypy --no-color-output src/ tests
  test:
    runs-on: [self-hosted, X64, Linux]
    env:
      POSTGRES_ID: test
      POSTGRES_PASSWORD: test
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 25432
      POSTGRES_DB: hyuabot
      PYTHONPATH: ./src
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ env.POSTGRES_ID }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 25432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      env:
        REQUIREMENTS_FILE: test
      run: |
        python -m pip install -U pip setuptools
        python -m pip install -U -r requirements/${REQUIREMENTS_FILE}.txt
    - name: Test with pytest
      run: |
        python -m pytest -m 'not integration' -v
  docker-image-build:
    runs-on: [self-hosted, ARM64, Linux]
    needs: [lint, typecheck, test]
    env:
      IMAGE_NAME: localhost:32000/hyuabot/hyuabot-subway-timetable-updater:latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Build Environment
      uses: docker/setup-buildx-action@v2
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        load: true
        tags: ${{ env.IMAGE_NAME }}
        no-cache: true
    - name: Push docker image
      run: |
        docker push ${{ env.IMAGE_NAME }}
    - name: Remove docker image
      run: |
        docker rmi ${{ env.IMAGE_NAME }}