name: Docker Image Build
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  docker-image-build:
    runs-on: [ self-hosted, ARM64, Linux ]
    env:
      IMAGE_NAME: localhost:32000/hyuabot/hyuabot-subway-timetable-updater:latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Build Environment
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: ${{ env.IMAGE_NAME }}
          no-cache: true
      - name: Push docker image
        run: |
          docker push ${{ env.IMAGE_NAME }}
      - name: Remove docker image
        run: |
          docker rmi ${{ env.IMAGE_NAME }}
